services:
  scraper:
    container_name: scraper
    image: scraper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=<uri>
      - MONGO_DB=animated_db
      - MAL_PAGES=10
      - GIFS_PER_ANIME=1000
    command: python3 scraper